### ISSUE TITLE
Support numeric characters in function/variable tokens

### ISSUE THREAD

**Issue by ratrabbit** [ilyastouyle/mathTokenizer#1]
I just found this npm package and is great, however we have some usecases where a variable/function might include numerical characters in it's name.
(Eg. `(P1 + C)/2` ). 

We are currently getting the following output:

```js
 [
  {
    "type": "lparenthesis",
    "value": "("
  },
  {
    "type": "variable",
    "value": "P"
  },
  {
    "type": "operator",
    "value": "*"
  },
  {
    "type": "operator",
    "value": "*"
  },
  {
    "type": "number",
    "value": "1"
  },
  {
    "type": "operator",
    "value": "+"
  },
  {
    "type": "variable",
    "value": "C"
  },
  {
    "type": "rparenthesis",
    "value": ")"
  },
  {
    "type": "operator",
    "value": "/"
  },
  {
    "type": "number",
    "value": "2"
  }
]
```

As of now, this can be easily avoided by forcing variables/functions to have only letters, but it may be worth it.

**Comment by ilyastouyle** [comment]
Thanks!
I was going to add support for custom variable names and constants in the next minor release.
Expect it some time this week!

**Comment by ilyastouyle** [comment]
The minor version is released!
Thanks!
